name: "Bundle"

on:
  workflow_dispatch:
  push:
    branches:
      - v1
    paths:
      - "modules/*.json"

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MODULES_REGISTRY_BOT_TOKEN }}
          ref: v1
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Set up foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Bundle
        run: |
          pnpm bundle
          pnpm format-bundle
          git config user.name modules-registry-bot
          git config user.email infra@hatsprotocol.xyz
          git add .
          git commit -m "automated bundle"
          git push
