name: "Bundle"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "modules/*.json"
      - "infra/*.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MODULES_REGISTRY_BOT_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - name: Set up foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Bundle
        run: |
          yarn bundle
          yarn format-bundle
          git config user.name modules-registry-bot
          git config user.email infra@hatsprotocol.xyz
          git add .
          git commit -m "automated bundle"
          git push
