name: "Test"

on: [pull_request]

env:
  GOERLI_RPC: https://goerli.infura.io/v3/${{ secrets.INFURA_KEY }}
  MAINNET_RPC: https://mainnet.infura.io/v3/${{ secrets.INFURA_KEY }}
  ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test ./test/goerliDeployments.test.ts
