name: "Test"

on:
  pull_request:
  workflow_dispatch:

env:
  SEPOLIA_RPC: https://ethereum-sepolia-rpc.publicnode.com
  MAINNET_RPC: https://cloudflare-eth.com
  POLYGON_RPC: https://polygon-rpc.com
  OPTIMISM_RPC: https://mainnet.optimism.io
  ARBITRUM_RPC: https://arb1.arbitrum.io/rpc
  GNOSIS_RPC: https://gnosis.publicnode.com
  BASE_RPC: https://mainnet.base.org
  PGN_RPC: https://rpc.publicgoods.network
  CELO_RPC: https://forno.celo.org
  ETHERSCAN_KEY: HDMPWG86NYEF1Y5KWZU1XI4HZX4SNHFW3B

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - name: Set up foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Check Format
        run: yarn prettier . --check
      - name: Test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn test
